feat(test): adds rudimentary e2e test framework using pytest
desec-io/desec-stack pull request #431
Opened 2020-08-24 13:25 UTC by nils-wisiol

2020-08-24 14:57 UTC, peterthomassen requested changes

2020-08-25 08:41 UTC, nils-wisiol commented on test/e2e2/conftest.py
> +        }  # e2e config skips email verification
done, I'm returning the whole response object now, in order to enable status code checks etc

2020-08-25 08:41 UTC, nils-wisiol commented on test/e2e2/spec/test_api_user_mgmt.py
> +    api_anon.register(email, password)
done

2020-08-25 08:41 UTC, nils-wisiol commented on test/e2e2/spec/test_api_user_mgmt.py
> +def test_register2(api_user: DeSECAPIV1Client):
a little annoying to do, but possible. However not needed right now

2020-08-26 11:19 UTC, peterthomassen approved these changes

2020-08-27 08:11 UTC, merged