Breaking News
desec-io/desec-stack pull request #465
Opened 2020-10-17 10:53 UTC by nils-wisiol

- remove old news
- add today's news
- minor modifications in the alert visualization

on my computer it looks like this

![image](https://user-images.githubusercontent.com/1026940/96335253-b512e880-1077-11eb-8147-89f0f74a462c.png)

2020-10-17 10:55 UTC, nils-wisiol commented
I fixed the wrong end-time to 10:13 am UTC, screenshot is outdated.

2020-10-17 12:01 UTC, peterthomassen requested changes

2020-10-17 12:01 UTC, peterthomassen commented on webapp/src/views/Home.vue
> +            'normal operations at 10:13 pm UTC. DNS operations continued throughout.',
```suggestion
            'normal operations at 10:13 am UTC. DNS operations continued throughout.',
```

2020-10-18 08:17 UTC, nils-wisiol commented
I fixed the e2e tests; I think this is good to merge now. :+1:

2020-10-18 09:16 UTC, peterthomassen approved these changes

2020-10-18 11:22 UTC, merged