fix(webapp): use strict equality
desec-io/desec-stack pull request #647
Opened 2023-01-04 18:20 UTC by Rotzbua

Use strict equality for type safety.

2023-01-06 18:33 UTC, peterthomassen requested changes
I think one of the changes causes problems (see comment at the respective code location).

All other changes are about comparisons where operand types are not under user control (e.g. the `.length` attribute of an array), so type safety is implicit because the operand is type-safe.

While I see that this change could be made, I'm not sure this is worth merging. -- I'm happy to be educated about the actual impact, or about a recent development where JavaScript folks feel that these changes are important.

Also, @nils-wisiol what do you think?

2023-01-06 18:33 UTC, peterthomassen commented on www/webapp/src/components/Field/Record/DNSKEY.vue
> +const equals3 = (value) => !value || value === 3;
Is this correct? -- The input field value is expected to be a string, so `=== 3` should always be false.

2023-01-06 20:12 UTC, Rotzbua commented
Thanks for the feedback. I reduced the changes to just type `String`. As you pointed out the compare with integer need way more investigation.

2023-01-10 08:17 UTC, nils-wisiol commented
Thanks for this work @Rotzbua! 

I believe less linter warnings are good, also because we do not have any automated tests for the webapp. Maintaining good code style will (a) produce less error-prone code and (b) unclog the linter output to see things that actually matter.

2023-01-10 08:19 UTC, nils-wisiol commented
Is there a way to integrate the linter in out GitHub actions? I do not think we can require zero warnings as of now. So ideally, PRs would be required to not produce more warnings than the code in main :)

2023-01-10 08:19 UTC, nils-wisiol approved these changes

2023-01-10 08:20 UTC, nils-wisiol commented
@peterthomassen this needs your approval for merging

2023-01-10 08:53 UTC, peterthomassen approved these changes

2023-01-10 09:25 UTC, merged

2023-01-10 10:55 UTC, Rotzbua commented
@nils-wisiol Unfortunately I don't know any tool which fulfills this. Otherwise I would have already created a PR ;)