refactor(webapp): remove unused tests
desec-io/desec-stack pull request #650
Opened 2023-01-06 21:25 UTC by Rotzbua

Tests are not used and properly configured. Remove for easier maintenance.

2023-01-06 21:32 UTC, peterthomassen approved these changes
Thank you for cleaning this up.

I'll be in vacation for the upcoming two weeks, and will take a closer look at everything soon after! So long, Peter

2023-01-06 21:36 UTC, Rotzbua commented
I wish you a good relaxation 👍

2023-01-26 13:06 UTC, peterthomassen requested changes
This produced a conflict with an earlier (now merged) PR of yours. Could you please rebase and resolve the conflict? thanks.

2023-01-26 14:45 UTC, peterthomassen approved these changes

2023-01-26 16:14 UTC, merged