refactor(webapp): captcha to component
desec-io/desec-stack pull request #754
Opened 2023-07-08 07:38 UTC by Rotzbua

Refactor redundant captcha code to one component.

## Reference

 #752

2023-07-08 08:12 UTC, Rotzbua commented
@peterthomassen First working draft for captcha. The proxy commit is just for testing and will be removed.

2024-01-11 16:48 UTC, peterthomassen commented
Display works fine. Submitting the captcha returns a 400 response with payload

```
{
    "captcha": {
        "id": [
            "This field is required."
        ],
        "solution": [
            "This field is required."
        ]
    }
}
```

DOM isn't updated after the 400 response (i.e. spinner moves indefinitely on submission button). Console says:
```
[Vue warn]: Error in callback for watcher "captcha_error": "TypeError: Cannot read properties of undefined (reading 'getCaptcha')"

found in

---> <ActivateAccountActionHandler> at /usr/src/app/src/components/ActivateAccountActionHandler.vue
       <VForm>
         <VCard>
           <ConfirmationPage> at /usr/src/app/src/views/ConfirmationPage.vue
             <VMain>
               <VApp>
                 <App> at /usr/src/app/src/App.vue
                   <Root>
warn @ chunk-TQVERUCE.js?v=08bf4eec:3674


TypeError: Cannot read properties of undefined (reading 'getCaptcha')
    at VueComponent.captcha_error (ActivateAccountActionHandler.vue:52:1)
    at invokeWithErrorHandling (chunk-TQVERUCE.js?v=08bf4eec:2396:26)
    at Watcher2.run (chunk-TQVERUCE.js?v=08bf4eec:2788:13)
    at flushSchedulerQueue (chunk-TQVERUCE.js?v=08bf4eec:3271:13)
    at Array.<anonymous> (chunk-TQVERUCE.js?v=08bf4eec:2481:12)
    at flushCallbacks (chunk-TQVERUCE.js?v=08bf4eec:2438:14)


[Vue warn]: Error in v-on handler (Promise/async): "TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function"

found in

---> <VForm>
       <VCard>
         <ConfirmationPage> at /usr/src/app/src/views/ConfirmationPage.vue
           <VMain>
             <VApp>
               <App> at /usr/src/app/src/App.vue
                 <Root>
```

2024-04-29 14:39 UTC, peterthomassen commented
Would you mind rebasing this? Then I'll take a another look.

2024-05-27 12:17 UTC, peterthomassen requested changes
Almost ready! Just two strings have been confused.

2024-05-27 12:17 UTC, peterthomassen commented on www/webapp/src/components/Field/GenericCaptcha.vue
> +      hintImage: 'Trouble hearing? Switch to an image CAPTCHA.',
Those two strings are swapped.

2024-05-27 12:17 UTC, peterthomassen commented on www/webapp/src/views/ResetPassword.vue
> +                                @update="(id, solution) => {captchaID=id; captchaSolution=solution}"
nice

2024-10-23 06:21 UTC, peterthomassen approved these changes

2024-10-28 10:01 UTC, merged