chore(webapp): migrate to vite 5
desec-io/desec-stack pull request #837
Opened 2023-11-19 22:35 UTC by Rotzbua

Guide:

https://vitejs.dev/guide/migration.html

Not fully tested yet.

2023-11-20 16:30 UTC, peterthomassen commented
Closes #805

2023-12-26 15:50 UTC, Rotzbua commented
@peterthomassen Works for me. Can you review? Happy xmas 🎄

2024-01-02 15:10 UTC, peterthomassen requested changes
Thanks! Looks mostly good; just minor stuff.

According to https://vitejs.dev/guide/migration#allow-path-containing-to-fallback-to-index-html, this also fixes #805. Can you confirm that's the case?

2024-01-02 15:10 UTC, peterthomassen commented on www/webapp/package.json
> +    "sass": "~1.32.13",
Why are we downgrading?

2024-01-02 15:10 UTC, peterthomassen commented on test/e2e2/spec/test_www.py
> +    # Source: https://github.com/vitejs/vite/tree/v5.2.0/packages/plugin-legacy#content-security-policy
404

2024-01-02 15:10 UTC, peterthomassen commented
> Happy xmas 🎄

Same to you, very much belated! And happy new year! :partying_face:

2024-01-08 13:52 UTC, peterthomassen approved these changes
lgtm, thanks a lot!

2024-01-08 14:34 UTC, merged